name: HTML Build
on:
  push:
    branches: master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: HTML build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      - name: Run build
        run: |
          npm install
          npx @11ty/eleventy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
